steps:
- name: 'maven:3.8.6-openjdk-18'
entrypoint: 'mvn'
args: ['install']
- name: maven:3-jdk-8
entrypoint: mvn
args: ['package','-Dmaven.test.skip=true']
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', 'gcr.io/personal-portfolio-356404/personal-portfolio', '.']